Repository Simperfy/CS-EXPO-2022, pull requests merged in 2022-01, with the labels that each got.

#17 [FIX]: False syntax error
  src/components/Carousel.jsx
  src/components/Carousel.tsx
  src/components/Hero.tsx
  src/pages/index.astro
Labels: fix

#19 [UPDATE]: Logo assets
  public/favicon.ico
  public/images/logo/64px.png
  src/components/Main/Header.jsx
  src/layouts/Main.astro
  src/styles/global.css
Labels: enhancement

#20 Updated Partners.astro, Centralized Strings, Bootstrap for Responsiveness
  src/components/Dictionaries/Strings.js
  src/layouts/Partners.astro
  src/pages/index.astro
  src/pages/partners.astro
  src/styles/partners.css
Labels: feature

#21 [UPDATE]: Home page
  public/images/placeholders/400x600.png
  src/components/Carousel.tsx
  src/components/CarouselPeople.tsx
  src/components/Dictionaries/Strings.js
  src/components/Hero.tsx
  src/components/HeroContainer.tsx
  src/components/Main/Header.jsx
  src/layouts/Partners.astro
  src/pages/index.astro
  src/pages/partners.astro
  src/styles/hero.css
  src/styles/heroContainer.css
  tailwind.config.cjs
Labels: enhancement

#22 Feat about
  src/components/CarouselPeople.tsx
  src/pages/about.astro
  src/pages/index.astro
  tailwind.config.cjs
Labels: enhancement, feature

#23 Gallery
  package-lock.json
  package.json
  src/components/CarouselGallery.tsx
  src/pages/gallery.astro
  tailwind.config.cjs
Labels: enhancement, feature
