Repository Simperfy/CS-EXPO-2022, pull requests merged in 2022-02, with the labels that each got.

#28 **Gallery with Images**
  public/images/gallery/cscon2k18/img2k18-1.JPG
  public/images/gallery/cscon2k18/img2k18-2.JPG
  public/images/gallery/cscon2k18/img2k18-3.jpg
  public/images/gallery/cscon2k18/img2k18-4.JPG
  public/images/gallery/cscon2k18/img2k18-5.JPG
  public/images/gallery/cscon2k18/img2k18-6.JPG
  public/images/gallery/cscon2k18/img2k18-7.JPG
  public/images/gallery/cscon2k18/img2k18-8.JPG
  public/images/gallery/cscon2k18/img2k18-9.JPG
  public/images/gallery/csconk217/During1.JPG
  public/images/gallery/csconk217/During2.JPG
  public/images/gallery/csconk217/During3.JPG
  public/images/gallery/csconk217/During4.JPG
  public/images/gallery/csconk217/During5.JPG
  public/images/gallery/csconk217/During6.JPG
  public/images/gallery/csconk217/Ignite1.JPG
  public/images/gallery/csconk217/Ignite2.JPG
  public/images/gallery/csconk217/ignite3.JPG
  src/components/CarouselGallery.tsx
  src/pages/gallery.astro
Labels: enhancement

#32 [UPDATE]: General Update (2)
  package-lock.json
  package.json
  public/images/gallery/cscon2k18/img2k18-1.jpg
  public/images/gallery/cscon2k18/img2k18-2.jpg
  public/images/gallery/cscon2k18/img2k18-4.jpg
  public/images/gallery/cscon2k18/img2k18-5.jpg
  public/images/gallery/cscon2k18/img2k18-6.jpg
  public/images/gallery/cscon2k18/img2k18-7.jpg
  public/images/gallery/cscon2k18/img2k18-8.jpg
  public/images/gallery/cscon2k18/img2k18-9.jpg
  public/images/gallery/csconk217/during1.jpg
  public/images/gallery/csconk217/during2.jpg
  public/images/gallery/csconk217/during3.jpg
  public/images/gallery/csconk217/during4.jpg
  public/images/gallery/csconk217/during5.jpg
  public/images/gallery/csconk217/during6.jpg
  public/images/gallery/csconk217/ignite1.jpg
  public/images/gallery/csconk217/ignite2.jpg
  public/images/gallery/csconk217/ignite3.jpg
  src/components/CarouselGallery.tsx
  src/components/CarouselPeople.tsx
  src/components/Hero.tsx
  src/components/Main/Header.jsx
  src/pages/about.astro
  src/pages/gallery.astro
  src/pages/index.astro
  src/pages/partners.astro
Labels: enhancement, fix

#34 [FIX]: Hero component responsiveness
  src/components/Hero.tsx
Labels: fix

#31 Update on About page
  public/images/about/about-hero.png
  public/images/about/committee/bernardo400x600.png
  public/images/about/committee/brielle400x600.jpg
  public/images/about/committee/fabian400x600.jpg
  public/images/about/committee/ferido400x600.png
  public/images/about/committee/jordan400x600.png
  public/images/about/committee/justine400x600.png
  public/images/about/committee/leuterio400x600.jpg
  public/images/about/committee/lim400x600.jpg
  public/images/about/committee/rizan400x600.jpg
  public/images/about/committee/tarronas400x600.jpg
  public/images/about/faculty/doc_shane400x600.jpg
  public/images/about/faculty/magpantay400x600.png
  public/images/about/faculty/miss_habal.jpg
  public/images/about/faculty/ms_adao400x600.png
  public/images/about/faculty/ms_may400x600.jpg
  public/images/about/faculty/sir_cheng.jpg
  public/images/about/faculty/sir_paculanan400x600.jpg
  src/components/About/CarouselFaculty.tsx
  src/components/CarouselPeople.tsx
  src/components/Dictionaries/AboutStrings.js
  src/pages/about.astro
Labels: enhancement

#38 [UPDATE]: carouselFaculty title spacing
  src/components/About/CarouselFaculty.tsx
Labels: enhancement

#40 [UPDATE]: Add animations to projects page
  src/pages/projects.astro
  src/styles/projects.css
Labels: enhancement

#41 UPDATE: Date in home page
  src/pages/index.astro
Labels: enhancement
